### Problem Statement: A cloth manufacturing company is interested to know about the segment or attributes causes high sale. 

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
#from sklearn import datasets  
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import classification_report
from sklearn import preprocessing

In [2]:
company = pd.read_csv('Company_data.csv')

In [3]:
company

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0     9.50        138      73           11         276    120       Bad   42   
1    11.22        111      48           16         260     83      Good   65   
2    10.06        113      35           10         269     80    Medium   59   
3     7.40        117     100            4         466     97    Medium   55   
4     4.15        141      64            3         340    128       Bad   38   
..     ...        ...     ...          ...         ...    ...       ...  ...   
395  12.57        138     108           17         203    128      Good   33   
396   6.14        139      23            3          37    120    Medium   55   
397   7.41        162      26           12         368    159    Medium   40   
398   5.94        100      79            7         284     95       Bad   50   
399   9.71        134      37            0          27    120      Good   49   

     Education Urban   US  
0           17   Yes  Yes  
1           10   Yes  Yes  
2           12   Yes  Yes  
3           14   Yes  Yes  
4           13   Yes   No  
..         ...   ...  ...  
395         14   Yes  Yes  
396         11    No  Yes  
397         18   Yes  Yes  
398         12   Yes  Yes  
399         16   Yes  Yes  

[400 rows x 11 columns]

In [4]:
company['Sales'] = np.where(company['Sales']>=8,'High','Low')

In [5]:
company

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0    High        138      73           11         276    120       Bad   42   
1    High        111      48           16         260     83      Good   65   
2    High        113      35           10         269     80    Medium   59   
3     Low        117     100            4         466     97    Medium   55   
4     Low        141      64            3         340    128       Bad   38   
..    ...        ...     ...          ...         ...    ...       ...  ...   
395  High        138     108           17         203    128      Good   33   
396   Low        139      23            3          37    120    Medium   55   
397   Low        162      26           12         368    159    Medium   40   
398   Low        100      79            7         284     95       Bad   50   
399  High        134      37            0          27    120      Good   49   

     Education Urban   US  
0           17   Yes  Yes  
1           10   Yes  Yes  
2           12   Yes  Yes  
3           14   Yes  Yes  
4           13   Yes   No  
..         ...   ...  ...  
395         14   Yes  Yes  
396         11    No  Yes  
397         18   Yes  Yes  
398         12   Yes  Yes  
399         16   Yes  Yes  

[400 rows x 11 columns]

In [6]:
label_encoder = preprocessing.LabelEncoder()
company['ShelveLoc']=label_encoder.fit_transform(company['ShelveLoc'])
company['Urban']=label_encoder.fit_transform(company['Urban'])
company['US']=label_encoder.fit_transform(company['US'])
company['Sales']=label_encoder.fit_transform(company['Sales'])

In [7]:
company

Sales  CompPrice  Income  Advertising  Population  Price  ShelveLoc  Age  \
0        0        138      73           11         276    120          0   42   
1        0        111      48           16         260     83          1   65   
2        0        113      35           10         269     80          2   59   
3        1        117     100            4         466     97          2   55   
4        1        141      64            3         340    128          0   38   
..     ...        ...     ...          ...         ...    ...        ...  ...   
395      0        138     108           17         203    128          1   33   
396      1        139      23            3          37    120          2   55   
397      1        162      26           12         368    159          2   40   
398      1        100      79            7         284     95          0   50   
399      0        134      37            0          27    120          1   49   

     Education  Urban  US  
0           17      1   1  
1           10      1   1  
2           12      1   1  
3           14      1   1  
4           13      1   0  
..         ...    ...  ..  
395         14      1   1  
396         11      0   1  
397         18      1   1  
398         12      1   1  
399         16      1   1  

[400 rows x 11 columns]

In [8]:
company['Sales'].value_counts()

1    236
0    164
Name: Sales, dtype: int64

In [9]:
array = company.values

In [10]:
array

array([[  0, 138,  73, ...,  17,   1,   1],
       [  0, 111,  48, ...,  10,   1,   1],
       [  0, 113,  35, ...,  12,   1,   1],
       ...,
       [  1, 162,  26, ...,  18,   1,   1],
       [  1, 100,  79, ...,  12,   1,   1],
       [  0, 134,  37, ...,  16,   1,   1]], dtype=int64)

In [11]:
X = array[:,1:]
Y = array[:,0]

In [12]:
# Random Forest Classification
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100, oob_score=True, max_features=3)
model.fit(X, Y)

RandomForestClassifier(max_features=3, oob_score=True)

In [13]:
# Accuracy 
accuracy = model.score(X, Y)
print(accuracy*100)

100.0


In [14]:
model.estimators_

[DecisionTreeClassifier(max_features=3, random_state=182367469),
 DecisionTreeClassifier(max_features=3, random_state=992890814),
 DecisionTreeClassifier(max_features=3, random_state=602037235),
 DecisionTreeClassifier(max_features=3, random_state=837657579),
 DecisionTreeClassifier(max_features=3, random_state=2047346346),
 DecisionTreeClassifier(max_features=3, random_state=433830082),
 DecisionTreeClassifier(max_features=3, random_state=915774831),
 DecisionTreeClassifier(max_features=3, random_state=1511480986),
 DecisionTreeClassifier(max_features=3, random_state=619820087),
 DecisionTreeClassifier(max_features=3, random_state=1978527815),
 DecisionTreeClassifier(max_features=3, random_state=962873481),
 DecisionTreeClassifier(max_features=3, random_state=2061620150),
 DecisionTreeClassifier(max_features=3, random_state=331069916),
 DecisionTreeClassifier(max_features=3, random_state=1515997200),
 DecisionTreeClassifier(max_features=3, random_state=1838603366),
 DecisionTreeClassi

In [15]:
model.oob_score_

0.8175

In [16]:
model.classes_

array([0, 1], dtype=int64)

In [17]:
company['Sales_pred']=model.predict(X)
company[['Sales','Sales_pred']]

Sales  Sales_pred
0        0           0
1        0           0
2        0           0
3        1           1
4        1           1
..     ...         ...
395      0           0
396      1           1
397      1           1
398      1           1
399      0           0

[400 rows x 2 columns]

In [18]:
company['Sales_pred'].value_counts()

1    236
0    164
Name: Sales_pred, dtype: int64

In [19]:
pd.crosstab(company['Sales'],company['Sales_pred'])

Sales_pred    0    1
Sales               
0           164    0
1             0  236

In [20]:
# Confusion Matrix for the model accuracy
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(company['Sales'],company['Sales_pred'])
confusion_matrix

array([[164,   0],
       [  0, 236]], dtype=int64)

In [21]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier

In [22]:
# Bagging
kfold = KFold(n_splits=10, random_state=7, shuffle=True)
cart = DecisionTreeClassifier()
model1 = BaggingClassifier(base_estimator=cart, n_estimators=100, random_state=7)
results1 = cross_val_score(model1, X, Y, cv=kfold)
print(results1.mean()*100)

81.0


In [23]:
# AdaBoost Classification
num_trees = 100
kfold = KFold(n_splits=10, random_state=7,shuffle=True)
model2 = AdaBoostClassifier(n_estimators=num_trees, random_state=7)
results2 = cross_val_score(model2, X, Y, cv=kfold)
print(results2.mean()*100)

88.25
